# Generated by Django 3.0.1 on 2021-10-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RehabMonthlyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=15)),
                ('beds_available', models.PositiveIntegerField()),
                ('bed_days', models.PositiveIntegerField()),
                ('patient_days', models.PositiveIntegerField()),
                ('hospitalized', models.PositiveIntegerField()),
                ('discharged_alive', models.PositiveIntegerField()),
                ('died_before_48_h', models.PositiveIntegerField()),
                ('died_after_48_h', models.PositiveIntegerField()),
                ('days_hospitalized', models.PositiveIntegerField()),
                ('referrals', models.PositiveIntegerField()),
                ('transfers', models.PositiveIntegerField()),
                ('self_discharged', models.PositiveIntegerField()),
                ('stayed_in_the_ward', models.PositiveIntegerField()),
                ('admissions', models.PositiveIntegerField()),
            ],
        ),
    ]
