<<<<<<< HEAD
# Generated by Django 3.2.7 on 2021-10-10 07:01
=======
# Generated by Django 3.0.1 on 2021-10-05 06:12
>>>>>>> origin/master

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='NICUPaeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(auto_created=True, max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('Beds_available', models.PositiveSmallIntegerField(default=0)),
                ('Bed_days', models.PositiveSmallIntegerField(default=0)),
                ('Patient_days', models.PositiveSmallIntegerField(default=0)),
                ('Hospitalized', models.PositiveSmallIntegerField(default=0)),
                ('Discharged_alive', models.PositiveSmallIntegerField(default=0)),
                ('Died_before_48h', models.PositiveSmallIntegerField(default=0)),
                ('Died_after_48h', models.PositiveSmallIntegerField(default=0)),
                ('Days_hospitalised', models.PositiveSmallIntegerField(default=0)),
                ('Referrals', models.PositiveSmallIntegerField(default=0)),
                ('Transfers', models.PositiveSmallIntegerField(default=0)),
                ('Self_discharged', models.PositiveSmallIntegerField(default=0)),
                ('Stayed_ward', models.PositiveSmallIntegerField(default=0)),
                ('Admissions', models.PositiveSmallIntegerField(default=0)),
=======
            name='RehabMonthlyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=15)),
                ('beds_available', models.PositiveIntegerField()),
                ('bed_days', models.PositiveIntegerField()),
                ('patient_days', models.PositiveIntegerField()),
                ('hospitalized', models.PositiveIntegerField()),
                ('discharged_alive', models.PositiveIntegerField()),
                ('died_before_48_h', models.PositiveIntegerField()),
                ('died_after_48_h', models.PositiveIntegerField()),
                ('days_hospitalized', models.PositiveIntegerField()),
                ('referrals', models.PositiveIntegerField()),
                ('transfers', models.PositiveIntegerField()),
                ('self_discharged', models.PositiveIntegerField()),
                ('stayed_in_the_ward', models.PositiveIntegerField()),
                ('admissions', models.PositiveIntegerField()),
>>>>>>> origin/master
            ],
        ),
    ]
