# Generated by Django 3.0.1 on 2021-10-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehabmonthlyrecord',
            name='admissions',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='rehabmonthlyrecord',
            name='bed_days',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='rehabmonthlyrecord',
            name='beds_available',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='rehabmonthlyrecord',
            name='days_hospitalized',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='rehabmonthlyrecord',
            name='died_after_48_h',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='rehabmonthlyrecord',
            name='died_before_48_h',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='rehabmonthlyrecord',
            name='discharged_alive',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='rehabmonthlyrecord',
            name='hospitalized',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='rehabmonthlyrecord',
            name='patient_days',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='rehabmonthlyrecord',
            name='referrals',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='rehabmonthlyrecord',
            name='self_discharged',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='rehabmonthlyrecord',
            name='stayed_in_the_ward',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='rehabmonthlyrecord',
            name='transfers',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
