# Generated by Django 3.2.7 on 2021-10-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NICUPaeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(auto_created=True, max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('Beds_available', models.PositiveSmallIntegerField(default=0)),
                ('Bed_days', models.PositiveSmallIntegerField(default=0)),
                ('Patient_days', models.PositiveSmallIntegerField(default=0)),
                ('Hospitalized', models.PositiveSmallIntegerField(default=0)),
                ('Discharged_alive', models.PositiveSmallIntegerField(default=0)),
                ('Died_before_48h', models.PositiveSmallIntegerField(default=0)),
                ('Died_after_48h', models.PositiveSmallIntegerField(default=0)),
                ('Days_hospitalised', models.PositiveSmallIntegerField(default=0)),
                ('Referrals', models.PositiveSmallIntegerField(default=0)),
                ('Transfers', models.PositiveSmallIntegerField(default=0)),
                ('Self_discharged', models.PositiveSmallIntegerField(default=0)),
                ('Stayed_ward', models.PositiveSmallIntegerField(default=0)),
                ('Admissions', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
