# Generated by Django 3.2.7 on 2021-10-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_maternitymonthlyrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maternitymonthlyrecord',
            old_name='labor_use_partograph',
            new_name='labor_use_partograph_cesarean',
        ),
        migrations.AddField(
            model_name='maternitymonthlyrecord',
            name='labor_use_partograph_normal',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
