# Generated by Django 3.2.7 on 2021-10-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_nicupaeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nicupaeds',
            name='Admissions',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nicupaeds',
            name='Bed_days',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nicupaeds',
            name='Beds_available',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nicupaeds',
            name='Days_hospitalised',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nicupaeds',
            name='Died_after_48h',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nicupaeds',
            name='Died_before_48h',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nicupaeds',
            name='Discharged_alive',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nicupaeds',
            name='Hospitalized',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nicupaeds',
            name='Patient_days',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nicupaeds',
            name='Referrals',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nicupaeds',
            name='Self_discharged',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nicupaeds',
            name='Stayed_ward',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nicupaeds',
            name='Transfers',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nicupaeds',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
