# Generated by Django 3.2.7 on 2021-09-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_records', '0002_auto_20210929_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
