# Generated by Django 3.2.7 on 2021-10-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211005_1951'),
        ('backend', '0003_auto_20211005_0012'),
    ]

    operations = [
    ]
