# Generated by Django 3.0.1 on 2021-09-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_records', '0003_alter_monthlyrecord_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RehabMonthlyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beds_available', models.PositiveIntegerField(max_length=500)),
                ('bed_days', models.PositiveIntegerField(max_length=1000)),
                ('patient_days', models.PositiveIntegerField(max_length=1000)),
                ('hospitalized', models.PositiveIntegerField(max_length=100)),
                ('discharged_alive', models.PositiveIntegerField(max_length=100)),
                ('died_before_48_h', models.PositiveIntegerField(max_length=100)),
                ('died_after_48_h', models.PositiveIntegerField(max_length=100)),
                ('days_hospitalized', models.PositiveIntegerField(max_length=1000)),
                ('referrals', models.PositiveIntegerField(max_length=500)),
                ('transfers', models.PositiveIntegerField(max_length=500)),
                ('self_discharged', models.PositiveIntegerField(max_length=100)),
                ('stayed_in_the_ward', models.PositiveIntegerField(max_length=500)),
                ('admissions', models.PositiveIntegerField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='monthlyrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
