# Generated by Django 3.2.7 on 2021-10-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_merge_0002_auto_20211005_1951_0003_auto_20211005_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maternitymonthlyrecord',
            old_name='days_hospitalised',
            new_name='days_hospitalized',
        ),
        migrations.RenameField(
            model_name='maternitymonthlyrecord',
            old_name='died_after_48h',
            new_name='died_after_48_h',
        ),
        migrations.RenameField(
            model_name='maternitymonthlyrecord',
            old_name='died_before_48h',
            new_name='died_before_48_h',
        ),
        migrations.RenameField(
            model_name='maternitymonthlyrecord',
            old_name='stayed_in_ward',
            new_name='stayed_in_the_ward',
        ),
        migrations.AlterField(
            model_name='monthlyrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rehabmonthlyrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
