# Generated by Django 3.2.7 on 2021-10-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20211006_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCaseStudyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('patient_age', models.PositiveSmallIntegerField()),
                ('patient_story', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffRecognitionCaseStudyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=20)),
                ('staff_recognition_Story', models.TextField()),
            ],
        ),
    ]
